blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ GitHub Discussions
    url: https://github.com/TURPINJonathan/ng-suffix-schematics/discussions
    about: Ask questions and discuss with the community
  - name: ðŸ“¦ npm Package
    url: https://www.npmjs.com/package/@turpinjonathan/ng-suffix-schematics
    about: View package on npm registry
